name: "mpei_doc_bot"
display_name: "Док из МЭИ"
description: "Общие вопросы про МЭИ"
prompt: "Действуй как помощник-консультант университета МЭИ. К какой из тем относится следующий вопрос пользователя: {question}? Верни только численный номер наиболее подходящей темы: {context}."
categories:
  common:
    name: "common"
    display_name: "Остальные вопросы"
    description: "Все вопросы и реплики,НЕ ОТНОСЯЩИЕСЯ к МЭИ, университету, его мероприятиям и учебному процессу, образованию в целом"
    prompt: "Действуй как помощник-администратор университета МЭИ. На вопрос посетителя {question} нужен вежливый ответ с напоминанием, что ожидаются вопросы, свзяанные с университетом МЭИ и образовательным порцессом"
  information:
    name: "information"
    display_name: "Общая информация"
    description: "Вопросы про фактический учебный процесс, кафедру, сроки учебных работ, проведение занятий, экзаменов, зачетов и практик, проставление оценок"
    prompt: "Действуй как помощник-консультант университета МЭИ. Доступные данные: {context}. Вопрос пользователя: {question}. Твой подробный ответ:"
    db_path: "./chroma_db"
    collection_name: "information"
    retriever: 
      score_threshold: 0.25
      k: 3
      s: 3
      t: 0
      next: 1
      bm25: "2/25"
  mpei_orders:
    name: "mpei_orders"
    display_name: "Приказы МЭИ 2024"
    description: "Вопросы про официальную информацию университета, общеуниверситетские мероприятия, события"
    prompt: "Действуй как помощник-консультант университета МЭИ. Доступные данные: {context}. Вопрос пользователя: {question}. Твой подробный ответ:"
    db_path: "./chroma_db"
    collection_name: "mpei_orders"
    retriever: 
      score_threshold: 0.185
      k: 6
      s: 2
      t: 1
      next: 1
      bm25: "3/100"
  obr_pravo:
    name: "obr_pravo"
    display_name: "Образовательное право"
    description: "Вопросы по образовательному праву, юридические вопросы про образование, уровни, стандарты, права"
    prompt: "Действуй как юрист-консультант университета. Доступные данные: {context}. Вопрос пользователя: {question}. Твой подробный ответ:"
    db_path: "./chroma_db"
    collection_name: "obr_pravo"
    retriever: 
      score_threshold: 0.185
      k: 3
      s: 3
      t: 0
      neighbours: [1500, 1000]    
  bars_lecturer:
    name: "bars_lecturer"
    display_name: "БаРС для сотрудников"
    description: "Вопросы по использованию системы БАРС для учета успеваемости, ведения электронного журнала, интерфейс системы БаРС"
    prompt: "Действуй как помощник-администратор университета МЭИ. Доступные данные: {context}. Вопрос пользователя: {question}. Твой подробный ответ:"
    db_path: "./chroma_db"
    collection_name: "bars_lecturer"
    retriever: 
      score_threshold: 0.185
      k: 3
      s: 3
      t: 0
      neighbours: [1500, 1000]
  common2:
    name: "common2"
    display_name: "Остальные вопросы"
    description: "Все остальные вопросы,НЕ ОТНОСЯЩИЕСЯ к университету и образованию"
    prompt: "Действуй как помощник-администратор университета МЭИ. На вопрос посетителя {question} нужен вежливый ответ с напоминанием, что ожидаются вопросы, свзяанные с университетом МЭИ и образовательным порцессом"
  

