categories:
  dpo_common:
    display_name: "ДПО Общие вопросы"
    prompt: "prompt_dpo"
    retriever: 
      score_threshold: 0.185
      k: 4
      s: 4
      t: 0
      next: 1
      bm25: "5/100"
default:
  knowledge_base: "ДПО Общие вопросы"
  db_path: "./chroma_db"
stoplist: ["Усманов", "Новак"]
bot_token: 7357901098:AAHdhZ2-2EzzvcIaLK0XqDj9e_BCmM8gYOI
giga_creds: Y2Y4NTQyOTItNWNiNy00YmIxLWJjZTUtZGU3YWZmMDY5MWNjOjJhNDE3MzM3LWZhYTUtNDNhYi05YjYzLWE4ZmE2ZDI3MjI1MQ==
